package hr.algebra.panel;

import hr.algebra.model.Movie;
import hr.algebra.model.MovieTableModel;
import hr.algebra.repository.Repository;
import hr.algebra.repository.RepositoryFactory;
import hr.algebra.utils.FileUtils;
import hr.algebra.utils.IconUtils;
import hr.algebra.utils.MessageUtils;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Kevin Furjan
 */
public class MoviePanel extends javax.swing.JPanel {
    
    Repository repository;
    MovieTableModel moviesTableModel;
    
    private Movie selectedMovie;
    
    private List<JLabel> errorLabels;
    private List<JTextComponent> validationFields;
    
    private static final String DIR = "assets";
    private static final Random RANDOM = new Random();
    
    private static final String IMAGE_PATH = "/placeholder/no_image.png";
    private static final String MOVIE_ADDED = "Movie added";
    private static final String MOVIE_UPDATED = "Movie has been updated!";
    private static final String CHOOSE_A_MOVIE = "Please choose a movie to update";
    private static final String NEW_MOVIE_ADDED = "New movie has been successfully added";
    private static final String WRONG_OPERATION = "Wrong operation";
    private static final String DELETE_MOVIE_TITLE = "Delete movie";
    private static final String MOVIE_UPDATED_TITLE = "Movie updated";
    private static final String MOVIE_PUBLISHED_DATE = "MoviePublishedDate";
    private static final String CONFIRM_MOVIE_DELETION = "Do you really want to delete this movie?";
    
    private static final String ERROR = "Error";
    private static final String DELETE_ERROR = "Unable to delete movie!";
    private static final String NEW_MOVIE_ERROR = "Unable to create new movie!";
    private static final String SET_ICON_ERROR = "Unable to set icon!";
    private static final String SHOW_MOVIE_ERROR = "Unable to show movie!";
    private static final String UPDATE_MOVIE_ERROR = "Unable to update movie!";
    private static final String UNRECOVERABLE_ERROR = "Unrecoverable error";
    private static final String CANNOT_INITIATE_THE_FORM = "Cannot initiate the form";

    /**
     * Creates new form MoviePanel
     */
    public MoviePanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMovies = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblPublishedDate = new javax.swing.JLabel();
        txtPublishedDate = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblOriginalName = new javax.swing.JLabel();
        txtOriginalName = new javax.swing.JTextField();
        lblLength = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        txtLink = new javax.swing.JTextField();
        lblLink = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        lblLengthError = new javax.swing.JLabel();
        lblLinkError = new javax.swing.JLabel();
        lblStartDateError = new javax.swing.JLabel();
        lblOriginalNameError = new javax.swing.JLabel();
        lblDescriptionError = new javax.swing.JLabel();
        lblPublishedDateError = new javax.swing.JLabel();
        lblTitleError = new javax.swing.JLabel();
        btnDeleteMovie = new javax.swing.JButton();
        btnAddMovie = new javax.swing.JButton();
        btnUpdateMovie = new javax.swing.JButton();
        txtPicturePath = new javax.swing.JTextField();
        btnChooseImage = new javax.swing.JButton();
        lblPoster = new javax.swing.JLabel();

        tbMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMoviesMouseClicked(evt);
            }
        });
        tbMovies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMoviesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbMovies);

        lblTitle.setText("Title");

        lblPublishedDate.setText("Published date");

        txtPublishedDate.setName("MoviePublishedDate"); // NOI18N

        lblDescription.setText("Description");

        lblOriginalName.setText("Original name");

        lblLength.setText("Length");

        lblLink.setText("Link");

        lblStartDate.setText("Start date");

        lblLengthError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLengthError.setForeground(new java.awt.Color(255, 51, 51));

        lblLinkError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLinkError.setForeground(new java.awt.Color(255, 51, 51));

        lblStartDateError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblStartDateError.setForeground(new java.awt.Color(255, 51, 51));

        lblOriginalNameError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblOriginalNameError.setForeground(new java.awt.Color(255, 51, 51));

        lblDescriptionError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDescriptionError.setForeground(new java.awt.Color(255, 51, 51));

        lblPublishedDateError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPublishedDateError.setForeground(new java.awt.Color(255, 51, 51));

        lblTitleError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitleError.setForeground(new java.awt.Color(255, 51, 51));

        btnDeleteMovie.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteMovie.setText("Delete");
        btnDeleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMovieActionPerformed(evt);
            }
        });

        btnAddMovie.setText("Add");
        btnAddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMovieActionPerformed(evt);
            }
        });

        btnUpdateMovie.setText("Update");
        btnUpdateMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMovieActionPerformed(evt);
            }
        });

        txtPicturePath.setEditable(false);
        txtPicturePath.setBackground(new java.awt.Color(204, 204, 204));
        txtPicturePath.setName(""); // NOI18N

        btnChooseImage.setText("Choose image");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });

        lblPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placeholder/no_image.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAddMovie, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addGap(79, 79, 79))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtOriginalName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPublishedDate, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDescription, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOriginalName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtPublishedDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTitleError)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblPublishedDateError)
                                                    .addComponent(lblDescriptionError)
                                                    .addComponent(lblOriginalNameError))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLength)
                                            .addComponent(txtLink)
                                            .addComponent(txtStartDate)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblStartDate)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLengthError)
                                            .addComponent(lblLinkError)
                                            .addComponent(lblStartDateError)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLength)
                                            .addComponent(btnUpdateMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblLink))
                                        .addGap(0, 9, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChooseImage))
                            .addComponent(lblPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitleError)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLength)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLengthError))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPublishedDate)
                                    .addComponent(lblLink))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPublishedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPublishedDateError))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLinkError)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescriptionError)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblStartDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStartDateError))))
                        .addComponent(lblOriginalName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOriginalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOriginalNameError))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 77, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChooseImage))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        
        Optional<File> file = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");
        if (file.isPresent()) {
            txtPicturePath.setText(file.get().getAbsolutePath());
            setIcon(lblPoster, file.get());
        }
    }//GEN-LAST:event_btnChooseImageActionPerformed

    private void btnAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMovieActionPerformed
        
        if (formValid()) {
            try {
                String localPicturePath = uploadPicture();
                Movie movie = new Movie(
                        txtTitle.getText().trim(),
                        LocalDateTime.parse(txtPublishedDate.getText().trim(), Movie.DATE_FORMATTER),
                        txtDescription.getText().trim(),
                        txtOriginalName.getText().trim(),
                        txtLength.getText().trim(),
                        localPicturePath,
                        txtLink.getText().trim(),
                        txtStartDate.getText().trim());
                
                repository.createMovie(movie);
                moviesTableModel.setMovies(repository.selectMovies());
                clearForm();
                
                MessageUtils.showInformationMessage(MOVIE_ADDED, NEW_MOVIE_ADDED);
            } catch (Exception ex) {
                Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage(ERROR, NEW_MOVIE_ERROR);
            }
        }
    }//GEN-LAST:event_btnAddMovieActionPerformed

    private void btnUpdateMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMovieActionPerformed
        
        if (selectedMovie == null) {
            MessageUtils.showInformationMessage(WRONG_OPERATION, CHOOSE_A_MOVIE);
            return;
        }
        
        if (formValid()) {
            try {
                if (selectedMovie.getPicturePath() == null
                        || !txtPicturePath.getText().trim().equals(selectedMovie.getPicturePath())) {
                    Files.deleteIfExists(Paths.get(selectedMovie.getPicturePath()));
                    String localPicturePath = uploadPicture();
                    selectedMovie.setPicturePath(localPicturePath);
                }
                
                selectedMovie.setTitle(txtTitle.getText().trim());
                selectedMovie.setPublishedDate(LocalDateTime.parse(txtPublishedDate.getText().trim(), Movie.DATE_FORMATTER));
                selectedMovie.setDescription(txtDescription.getText().trim());
                selectedMovie.setOriginalName(txtOriginalName.getText().trim());
                selectedMovie.setLength(txtLength.getText().trim());
                selectedMovie.setLink(txtLink.getText().trim());
                selectedMovie.setStartDate(txtStartDate.getText().trim());
                
                repository.updateMovie(selectedMovie.getId(), selectedMovie);
                moviesTableModel.setMovies(repository.selectMovies());
                
                clearForm();
                
                MessageUtils.showInformationMessage(MOVIE_UPDATED_TITLE, MOVIE_UPDATED);
            } catch (Exception ex) {
                Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage(ERROR, UPDATE_MOVIE_ERROR);
            }
        }
    }//GEN-LAST:event_btnUpdateMovieActionPerformed

    private void btnDeleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMovieActionPerformed
        
        if (selectedMovie == null) {
            MessageUtils.showInformationMessage(WRONG_OPERATION, CHOOSE_A_MOVIE);
            return;
        }
        if (MessageUtils.showConfirmDialog(DELETE_MOVIE_TITLE, CONFIRM_MOVIE_DELETION) == JOptionPane.YES_OPTION) {
            try {
                Files.deleteIfExists(Paths.get(selectedMovie.getPicturePath()));
                
                repository.deleteMovie(selectedMovie.getId());
                moviesTableModel.setMovies(repository.selectMovies());
                
                clearForm();
            } catch (Exception ex) {
                Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage(ERROR, DELETE_ERROR);
            }
        }
    }//GEN-LAST:event_btnDeleteMovieActionPerformed

    private void tbMoviesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMoviesKeyReleased
        showMovie();
    }//GEN-LAST:event_tbMoviesKeyReleased

    private void tbMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMoviesMouseClicked
        showMovie();
    }//GEN-LAST:event_tbMoviesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMovie;
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnDeleteMovie;
    private javax.swing.JButton btnUpdateMovie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescriptionError;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblLengthError;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblLinkError;
    private javax.swing.JLabel lblOriginalName;
    private javax.swing.JLabel lblOriginalNameError;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblPublishedDate;
    private javax.swing.JLabel lblPublishedDateError;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblStartDateError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleError;
    private javax.swing.JTable tbMovies;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtOriginalName;
    private javax.swing.JTextField txtPicturePath;
    private javax.swing.JTextField txtPublishedDate;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    private void init() {
        
        try {
            initValidation();
            initRepository();
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage(UNRECOVERABLE_ERROR, CANNOT_INITIATE_THE_FORM);
            System.exit(1);
        }
    }
    
    private void initValidation() {
        
        errorLabels = Arrays.asList(lblTitleError, lblPublishedDateError, lblDescriptionError, lblOriginalNameError,
                lblLengthError, lblLinkError, lblStartDateError);
        
        validationFields = Arrays.asList(txtTitle, txtPublishedDate, txtDescription, txtOriginalName,
                txtLength, txtLink, txtStartDate);
    }
    
    private void initRepository() throws Exception {
        
        repository = RepositoryFactory.getRepository();
    }
    
    private void initTable() throws Exception {
        
        tbMovies.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbMovies.setAutoCreateRowSorter(true);
        tbMovies.setRowHeight(25);
        moviesTableModel = new MovieTableModel(repository.selectMovies());
        tbMovies.setModel(moviesTableModel);
    }
    
    private boolean formValid() {
        
        boolean formOk = true;
        
        for (int i = 0; i < validationFields.size(); i++) {
            formOk &= !validationFields
                    .get(i)
                    .getText()
                    .trim()
                    .isEmpty();
            
            errorLabels
                    .get(i)
                    .setText(validationFields
                            .get(i)
                            .getText()
                            .trim()
                            .isEmpty() ? "X" : "");
            
            if (MOVIE_PUBLISHED_DATE.equals(validationFields.get(i).getName())) {
                try {
                    LocalDateTime.parse(validationFields
                            .get(i)
                            .getText()
                            .trim(), Movie.DATE_FORMATTER);
                    
                    errorLabels
                            .get(i)
                            .setText("");
                } catch (Exception ex) {
                    formOk = false;
                    
                    errorLabels
                            .get(i)
                            .setText("X");
                }
            }
        }
        
        return formOk;
    }
    
    private void showMovie() {
        
        clearForm();
        int selectedRow = tbMovies.getSelectedRow();
        int rowIndex = tbMovies.convertRowIndexToModel(selectedRow);
        int selectedMovieId = (int) moviesTableModel.getValueAt(rowIndex, 0);
        
        try {
            Optional<Movie> optionalMovie = repository.selectMovie(selectedMovieId);
            if (optionalMovie.isPresent()) {
                selectedMovie = optionalMovie.get();
                fillForm(selectedMovie);
            }
        } catch (Exception ex) {
            Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage(ERROR, SHOW_MOVIE_ERROR);
        }
    }
    
    private void clearForm() {
        
        validationFields.forEach(e -> e.setText(""));
        errorLabels.forEach(e -> e.setText(""));
        
        selectedMovie = null;
        lblPoster.setIcon(new ImageIcon(getClass().getResource(IMAGE_PATH)));
    }
    
    private String uploadPicture() throws IOException {
        
        String picturePath = txtPicturePath.getText().trim();
        String ext = picturePath.substring(picturePath.lastIndexOf("."));
        String pictureName = Math.abs(RANDOM.nextInt()) + ext;
        String localPicturePath = DIR + File.separator + pictureName;
        FileUtils.copy(picturePath, localPicturePath);
        return localPicturePath;
    }
    
    private void fillForm(Movie movie) {
        
        if (movie.getPicturePath() != null && Files.exists(Paths.get(movie.getPicturePath()))) {
            txtPicturePath.setText(movie.getPicturePath());
            setIcon(lblPoster, new File(movie.getPicturePath()));
        } else {
            txtPicturePath.setText("");
            lblPoster.setIcon(new ImageIcon(getClass().getResource(IMAGE_PATH)));
        }
        
        txtTitle.setText(movie.getTitle());
        txtPublishedDate.setText(movie.getPublishedDate().format(Movie.DATE_FORMATTER));
        txtDescription.setText(movie.getDescription());
        txtOriginalName.setText(movie.getOriginalName());
        txtLength.setText(movie.getLength());
        txtLink.setText(movie.getLink());
        txtStartDate.setText(movie.getStartDate());
    }
    
    private void setIcon(JLabel label, File file) {
        
        try {
            Optional<ImageIcon> icon = IconUtils.createIcon(file.getAbsolutePath(), label.getWidth(), label.getHeight());
            if (icon.isPresent()) {
                label.setIcon(icon.get());
            }
        } catch (IOException | NullPointerException ex) {
            Logger.getLogger(MoviePanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage(ERROR, SET_ICON_ERROR);
        }
    }
}
